### ISSUE TITLE
Minor script issues

### ISSUE THREAD

**Issue by burner1024** [flamewing/WTPFamiliars#4]
1. I see massive ORs for statechecks in familiar scripts. ORs are slow. It's possible to combine state checks bitwise, which will increase both efficiency and readability. See BG2fixpack's CD_STATE_NOTVALID for an example.
2. I'm fairly certain that ActuallyInCombat can give false results, although I can't find a link to back that up. CombatCounterLT worked the best for me.

**Comment by flamewing** [comment]
I fixed point 1; I won't worry about the point 2 because there is another check if the familiar summoner is seeing any enemies.
