### ISSUE TITLE
Some love for linux?

### ISSUE THREAD

**Issue by burner1024** [flamewing/WTPFamiliars#5]
As far as I can tell, the only two missing things for proper linux support is lowercasing and adding a bash script to do the decoding. How about that?

**Comment by flamewing** [comment]
Can do; I was already thinking about doing the lowercasing anyway due to OCD reasons.

**Comment by flamewing** [comment]
Should be working, but I have no real way of testing on Linux; can you give it a spin? It expects oggenc to be available on the system.

**Comment by burner1024** [comment]
Installs and uninstalls fine, thanks. Except that top dir still needs to be lowercased.

Edit, oh, and as for a real way of testing on Linux, there's [Golem](https://golem.bgforge.net/).

**Comment by flamewing** [comment]
Thanks for the suggestion, I'll look into Golem.
